name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Vite dev server
      run: npm run dev
      env:
        NODE_ENV: development

    - name: Run Node server
      run: node server.cjs
      env:
        NODE_ENV: development
